public enum ParserValidationStatus {
    COMPATIBLE,
    INVALID_PLUGIN,
    INVALID_SOURCE,
    INCOMPATIBLE_PLUGIN_API,
    DUPLICATE_PARSER_ID,
    MISSING_PARSER_IMPLEMENTATION,
    PARSER_INITIALIZATION_FAILED,
    MISSING_DEPENDENCY,
    MISSING_COMPILER,
    COMPILATION_FAILED,
    INVALID_METADATA,
    DISABLED
}
